config/routes.rb
Kickstarter::Application.routes.draw do
  resources :subscriptions, only: [:new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  root :to => 'projects#index'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
  end
  match 'auth/:provider/callback', to: 'sessions#facebook_create', provider: 'facebook', via: [:get, :post], as: :facebook_callback
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  match "/contacts/gmail/get_contacts", controller: "contacts", action: "gmail_callback", via: [:get, :post]
  match "/contacts/failure", controller: "contacts", action: "failure", via: [:get, :post]
  post "send_email", controller: "contacts"
  namespace :payment do
    namespace :stripe do
      get "charges/new_card"
      post "charges", controller: 'charges', action: 'create_card'
    end
    namespace :paypal do
      match "notify", controller: 'notifications', action: 'create', via: [:get, :post]
    end
  end

  match 'search', controller: 'searches', action: 'search', via: :get, as: :search_results

  resources :projects do
    get "/contacts_import_instructions", controller: "contacts", action: "import_instructions", on: :member
    get "/get_gmail_contacts", controller: "contacts", action: "get_gmail_contacts", on: :member
    match 'category/:category', action: 'category', via: [:get, :post], on: :collection
    match 'location/:location', action: 'location', via: [:get, :post], on: :collection
    get 'rewards/choose', on: :member, controller: 'rewards', action: 'choose'
    get 'this_week', on: :collection
    get 'new_message', on: :member, as: :new_message
    get 'back', on: :member
    get 'pledge', controller: 'pledges', action: 'new', on: :member
    post 'create_pledge', controller: 'pledges', action: 'create', on: :member
    get 'new_reward', on: :collection
    get 'new_image', on: :collection
    get 'story', controller: 'stories', action: 'new', on: :member
    get 'info', on: :member
    get 'rewards', controller: 'rewards', action: 'new', on: :member
    patch 'create_story', controller: 'stories', action: 'create', on: :member
    patch 'create_info', on: :member
    patch 'create_rewards', controller: 'rewards', action: 'create', on: :member
    get 'admin_conversation', controller: 'admin/messages', action: 'index', on: :member
    post 'create_admin_conversation', controller: 'admin/messages', action: 'create', on: :member
    get 'description', on: :member
    get 'backers', on: :member
  end
  get "my_projects", to: 'projects#user_owned'

  get '/admin', controller: 'sessions', action: 'new', as: :admin_root
  namespace :admin do
    get "users", action: 'index', controller: :users
    delete "users", action: 'destroy', controller: :users
    post "users/:id/make_admin", action: 'make_admin', controller: :users, as: :make_admin
    resources :projects, only: [:index] do
      get "approve", on: :member
      get "reject", on: :member
    end
  end

  resources :messages, only: [:index, :show] do
    post "create", on: :member, as: :create
  end

  resources :users, only: [:create, :show, :update] do
    get "signup", to: 'users#new', on: :collection
    get "/edit_profile", to: 'users#edit', as: :edit, on: :member
  end

  

end

app/models/reward.rb
# == Schema Information
#
# Table name: rewards
#
#  id                    :integer          not null, primary key
#  minimum_amount        :integer
#  description           :text
#  estimated_delivery_on :date
#  quantity              :integer
#  created_at            :datetime
#  updated_at            :datetime
#  project_id            :integer
#  remaining_quantity    :integer
#

class Reward < ActiveRecord::Base
  after_save ThinkingSphinx::RealTime.callback_for(:project, [:project])
  after_destroy ThinkingSphinx::RealTime.callback_for(:project, [:project])
  before_save :update_remaining_quantity, if: -> { project.draft? || project.submitted? }

  validates :minimum_amount, :description, :estimated_delivery_on, presence: true
  validates :minimum_amount, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_blank: true
  validate :remaining_is_less_than_or_equal_to_quantity
  # validate :estimated_delivery_date
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true
  validate :remaining_quantity_positive

  belongs_to :project
  has_one :requested_reward, inverse_of: :reward

  def remaining_quantity_positive
    if remaining_quantity < 0
      requested_reward.errors.add :base, "Selected quantity should be less than remaining quantity"
      raise ActiveRecord::RecordNotSaved, requested_reward
    end
  end

  def update_remaining_quantity
    self.remaining_quantity = quantity if quantity.present? && quantity != 0
  end

  def estimated_delivery_date
    if estimated_delivery_on.nil? || estimated_delivery_on < Time.current
      errors.add :estimated_delivery_on, 'has to be after today'
    end
  end

  def remaining_is_less_than_or_equal_to_quantity
    if remaining_quantity.present? && remaining_quantity > quantity
      errors.add :remaining_quantity, 'should be less than or equal to quantity'
    end
  end


end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  include Projects::Callbacks

  before_action :set_project, only: [:new, :create]
  before_action :validate_owner, only: [:new, :create]

  def new
    if @project.rewards.empty?
      @reward = @project.rewards.build
    else
      @reward = @project.rewards
    end
  end

  def create
    if @project.save_rewards(project_params)
      redirect_to project_path(@project), notice: "Project #{@project.title} was successfully created/updated."
    else
      render action: :new
    end
  end

  private

    def project_params
      params.require(:project).permit(:rewards_attributes => [:id, :minimum_amount, :description, :estimated_delivery_on, :shipping, :quantity])
    end

end

app/views/rewards/_fields.html.erb
  <div class="control-group">
    <%= f.label "Amount", :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.text_field :minimum_amount, :class => 'text_field', :required => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.text_area :description, :class => 'text', :required => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :estimated_delivery_on, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.date_select :estimated_delivery_on, :class => 'date_field', :start_year => Time.current.year, :order => [:month, :year]  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :quantity, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :quantity, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <span class='required'>*</span><span> marks required fields</span>
    </div>
  </div>

app/views/rewards/_project_fields.html.erb
<%- @time = Time.current.to_i %>
<div class="control-group">
    <label class="control-label" for="project_rewards_attributes_<%= @time %>_minimum_amount">Amount</label>
    <span class='required'>*</span>
    <div class="controls">
      <input class="text_field" id="project_rewards_attributes_<%= @time %>_minimum_amount" name="project[rewards_attributes][<%= @time %>][minimum_amount]" type="text" required="required" />
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="project_rewards_attributes_<%= @time %>_description">Description</label>
    <span class='required'>*</span>
    <div class="controls">
      <textarea class="text" id="project_rewards_attributes_<%= @time %>_description" name="project[rewards_attributes][<%= @time %>][description]" required="required" >
</textarea>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="project_rewards_attributes_<%= @time %>_estimated_delivery_on">Estimated delivery on</label>
    <span class='required'>*</span>
    <div class="controls">
      <input id="project_rewards_attributes_<%= @time %>_estimated_delivery_on_3i" name="project[rewards_attributes][<%= @time %>][estimated_delivery_on(3i)]" type="hidden" value="1" />
<% @months = [] %>
<% (1..12).each {|m| @months << [Date::MONTHNAMES[m], m]} %>
<select id="project_rewards_attributes_<%= @time %>_estimated_delivery_on_2i" name="project[rewards_attributes][<%= @time %>][estimated_delivery_on(2i)]">
  <%= options_for_select @months, selected: Time.current.month %>
</select>
<% @years = (Time.current.year..(Time.current.year + 5)).to_a %>
<select id="project_rewards_attributes_<%= @time %>_estimated_delivery_on_1i" name="project[rewards_attributes][<%= @time %>][estimated_delivery_on(1i)]">
  <%= options_for_select @years, selected: Time.current.year %>
</select>

    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="project_rewards_attributes_<%= @time %>_quantity">Quantity</label>
    <div class="controls">
      <input class="text_field" id="project_rewards_attributes_<%= @time %>_quantity" name="project[rewards_attributes][<%= @time %>][quantity]" type="text" />
    </div>
  </div>

app/views/rewards/_show_fields.html.erb
<dl class="dl-horizontal">
  <dt><strong>Amount :</strong></dt>
  <dd><%= reward.minimum_amount %></dd>
  <dt><strong>Description:</strong></dt>
  <dd><%= reward.description %></dd>
  <dt><strong>Estimated delivery on:</strong></dt>
  <dd><%= reward.estimated_delivery_on %></dd>
  <dt><strong>Quantity:</strong></dt>
  <dd><%= reward.quantity %></dd>
  <dt><strong>Remaining Quantity:</strong></dt>
  <dd><%= reward.remaining_quantity %></dd>
</dl>

app/views/rewards/new.html.erb
<% @project.rewards.each_with_index do |reward, index| %>
  <%- error_message = "<h2>" + pluralize(reward.errors.count, "error") + " prohibited reward " + (index + 1).to_s + " from being saved:</h2>" -%>
  <%= get_errors(reward, error_message) %>
<% end %>
<%= form_for @project, url: create_rewards_project_path, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="highlight">
    <h4>Rewards</h4>
    <% counter = 0 %>
    <div class="project-reward">
      <%= f.fields_for :rewards, @reward do |builder| %>
      <h5>Reward #<%= counter = counter + 1 %></h5>
        <%= render partial: 'rewards/fields', :locals => { :f => builder } %>
      <% end %>
    </div>
    <div class="add-link">
      <%= link_to "Add Reward", new_reward_projects_path, remote: true %>
    </div>
  </div>

  <%= render partial: 'projects/steps_covered' %>

  <div class="form-actions">
    <%= link_to "< Prev", info_project_path(@project), :class => 'btn' %>
    <%= f.submit "Submit Project", :class => 'btn btn-primary' %>
  </div>
<% end %>