config/routes.rb
Kickstarter::Application.routes.draw do
  resources :subscriptions, only: [:new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  root :to => 'projects#index'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
  end
  match 'auth/:provider/callback', to: 'sessions#facebook_create', provider: 'facebook', via: [:get, :post], as: :facebook_callback
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  match "/contacts/gmail/get_contacts", controller: "contacts", action: "gmail_callback", via: [:get, :post]
  match "/contacts/failure", controller: "contacts", action: "failure", via: [:get, :post]
  post "send_email", controller: "contacts"
  namespace :payment do
    namespace :stripe do
      get "charges/new_card"
      post "charges", controller: 'charges', action: 'create_card'
    end
    namespace :paypal do
      match "notify", controller: 'notifications', action: 'create', via: [:get, :post]
    end
  end

  match 'search', controller: 'searches', action: 'search', via: :get, as: :search_results

  resources :projects do
    get "/contacts_import_instructions", controller: "contacts", action: "import_instructions", on: :member
    get "/get_gmail_contacts", controller: "contacts", action: "get_gmail_contacts", on: :member
    match 'category/:category', action: 'category', via: [:get, :post], on: :collection
    match 'location/:location', action: 'location', via: [:get, :post], on: :collection
    get 'rewards/choose', on: :member, controller: 'rewards', action: 'choose'
    get 'this_week', on: :collection
    get 'new_message', on: :member, as: :new_message
    get 'back', on: :member
    get 'pledge', controller: 'pledges', action: 'new', on: :member
    post 'create_pledge', controller: 'pledges', action: 'create', on: :member
    get 'new_reward', on: :collection
    get 'new_image', on: :collection
    get 'story', controller: 'stories', action: 'new', on: :member
    get 'info', on: :member
    get 'rewards', controller: 'rewards', action: 'new', on: :member
    patch 'create_story', controller: 'stories', action: 'create', on: :member
    patch 'create_info', on: :member
    patch 'create_rewards', controller: 'rewards', action: 'create', on: :member
    get 'admin_conversation', controller: 'admin/messages', action: 'index', on: :member
    post 'create_admin_conversation', controller: 'admin/messages', action: 'create', on: :member
    get 'description', on: :member
    get 'backers', on: :member
  end
  get "my_projects", to: 'projects#user_owned'

  get '/admin', controller: 'sessions', action: 'new', as: :admin_root
  namespace :admin do
    get "users", action: 'index', controller: :users
    delete "users", action: 'destroy', controller: :users
    post "users/:id/make_admin", action: 'make_admin', controller: :users, as: :make_admin
    resources :projects, only: [:index] do
      get "approve", on: :member
      get "reject", on: :member
    end
  end

  resources :messages, only: [:index, :show] do
    post "create", on: :member, as: :create
  end

  resources :users, only: [:create, :show, :update] do
    get "signup", to: 'users#new', on: :collection
    get "/edit_profile", to: 'users#edit', as: :edit, on: :member
  end

  

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  summary       :string(300)
#  location_name :string(255)
#  duration      :integer
#  deadline      :datetime
#  goal          :integer
#  created_at    :datetime
#  updated_at    :datetime
#  owner_id      :integer
#  category_id   :integer
#  published_at  :datetime
#  video_url     :string(255)
#  project_state :string(255)
#  permalink     :string(255)
#  deleted_at    :time
#  location_id   :integer
#

class Project < ActiveRecord::Base
  include ThinkingSphinx::Scopes
  after_save ThinkingSphinx::RealTime.callback_for(:project)
  after_destroy ThinkingSphinx::RealTime.callback_for(:project)

  with_options if: -> { first_step? || step_not_set? } do |project|
    project.validates :title, uniqueness: { case_sensitive: false }, length: { maximum: 60 }
    project.validates :title, :summary, :location, presence: true
    project.validates :summary, length: { maximum: 300 }
    project.validates_associated :location
  end

  with_options if: -> { third_step? || step_not_set? } do |project|
    project.validates :goal, :duration, :published_at, presence: true
    project.validates :goal, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_blank: true
    project.validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: PAYMENT_HOLDING_PERIOD }, allow_blank: true
    # project.validate :future_publish_date
  end
  
  validates_associated :story, if: -> { second_step? || step_not_set? }
  validates_associated :rewards, if: -> { fourth_step? || step_not_set? }

  has_many :rewards
  has_one :story, validate: false
  belongs_to :owner, foreign_key: "owner_id", class_name: 'User'
  belongs_to :category
  has_many :messages
  belongs_to :location, validate: false
  has_many :images, inverse_of: :project
  has_many :pledges, -> { joins(:transaction) }
  has_many :backers, -> { uniq },through: :pledges, source: :user

  accepts_nested_attributes_for :rewards, update_only: true
  accepts_nested_attributes_for :story, update_only: true
  accepts_nested_attributes_for :location, update_only: true
  accepts_nested_attributes_for :messages
  accepts_nested_attributes_for :images, reject_if: proc { |attributes| attributes[:attachment].blank? }
  accepts_nested_attributes_for :pledges

  scope :published, ->(time) { where(['published_at <= ?', time]) }
  scope :published_between, ->(start_time, end_time) { where(['published_at <= ? OR published_at >= ?', start_time, end_time]) }
  scope :still_active, -> { where(['deadline >= ?', Time.current]) }
  scope :located_in, ->(place) { joins(:location).where(:locations => { name: place}) }
  scope :owned_by, ->(user) { where(owner_id: user.id) }
  scope :live, -> { approved.published(Time.current).still_active }
  scope :live_for_user, ->(user) { live.where(owner_id: user.id) }
  scope :pending_for_approval, -> { submitted.still_active.order('created_at ASC') }
  scope :live_this_week, -> { approved.published_between(Time.current, 1.week.ago).still_active }
  scope :for_page, ->(page_number) { page(page_number).per_page(PER_PAGE) }

  sphinx_scope(:been_approved) { { :conditions => { :project_state => 'approved' } } }
  sphinx_scope(:active) { { :with => { :deadline => Time.current..1.month.from_now, :published_at => 1.month.ago..Time.current } } }

  before_save :set_deadline
  before_save :convert_to_youtube_embed_link

  acts_as_paranoid

  has_permalink :title, true

  include AASM

  aasm column: 'project_state' do
    state :draft, initial: true
    state :submitted
    state :approved
    state :rejected
    state :funding_successful
    state :funding_unsuccessful

    event :submit do
      transitions :from => :draft, :to => :submitted
    end

    event :approve do
      before do
        self.published_at = Time.current if published_at.nil? || published_at < Time.current
        self.deadline = published_at + duration.days
      end
      transitions :from => :submitted, :to => :approved
      after do
        set_publishing_delayed_job
        set_funding_delayed_job
      end
    end

    event :edit do
      transitions :from => :submitted, :to => :draft
    end

    event :reject do
      transitions :from => :submitted, :to => :rejected
    end

    event :completely_funded do
      transitions :from => :approved, :to => :funding_successful
      after do
        ProjectStatusNotifier.funded(self).deliver
      end
    end

    event :failed_funding_goal do
      transitions :from => :approved, :to => :funding_unsuccessful
      after do
        ProjectStatusNotifier.failed(self).deliver
      end
    end

  end

  # Converts any standard youtube link to equivalent embed link
  # eg. Youtube Link: http://www.youtube.com/watch?v=8SbUC-UaAxE&list=TLzRodY7MxKM0Hs7zgM0ueePM1_MzGI3h5
  # Embed Link: http://www.youtube.com/embed/8SbUC-UaAxE
  def convert_to_youtube_embed_link
    self.video_url.gsub!(/(youtube.com\/)(.)*v=([\w\-_]+)(.)*$/, '\1embed/\3')
  end

  def set_deadline
    if fourth_step?
      self.deadline = Time.current + duration.to_i.days
    end
  end

  def future_publish_date
    if published_at.nil? || published_at < Time.current
      errors.add :published_at, 'has to be after today'
    end
  end

  def step?(number)
    step == number
  end

  def step_not_set?
    step.nil?
  end

  def first_step?
    step?(1)
  end

  def second_step?
    step?(2)
  end

  def third_step?
    step?(3)
  end

  def fourth_step?
    step?(4)
  end

  def set_publishing_delayed_job
    Delayed::Job.enqueue(PublishProjectJob.new(self), run_at: published_at)
  end

  def set_funding_delayed_job
    Delayed::Job.enqueue(ProjectFundingJob.new(self), run_at: deadline)
  end

  def owner?(user)
    owner_id == user.id
  end

  def save_primary_details(project_creator)
    generate_permalink!
    self.owner = project_creator
    self.step = 1
    save
  end

  def save_story(params)
    self.step = 2
    update(params)
  end

  def save_info(params)
    self.step = 3
    update(params)
  end

  def save_rewards(params)
    self.step = 4
    update(params)
    submit!
  end

  def outdated?
    deadline <= Time.current
  end

  def thumbnail
    if images.present?
      images[0].attachment.url(:thumb)
    else
      '/images/thumb/missing.png'
    end
  end

  def youtube_video?
    video_url.present? && video_url.match(/youtube\.com/)
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  include Projects::Callbacks

  before_action :set_project, only: [:approve, :reject]

  def index
    @projects = Project.includes(:images).order('updated_at DESC').page(params[:page]).per_page(PER_PAGE)
  end

  def approve
    unless @project.approve!
      flash[:alert] = 'The project could not be approved'
      #FIXME_AB: Why do we need render js in these two actions, we have the erb.js files for these actions
      #FIXED: In case project fails to be accepted or rejected, it should display error message and not js.erb file
      render js: %(window.location.href = '#{ project_path(@project) }')
    end
  end

  def reject
    unless @project.reject!
      flash[:alert] = 'The project failed to be rejected'
      render js: %(window.location.href = '#{ project_path(@project) }')
    end
  end

end

app/controllers/concerns/projects/callbacks.rb
module Projects
  module Callbacks

    private

      def set_project
        unless (@project = Project.find_by_permalink(params[:id]))
          redirect_to root_path, alert: "No Project Found"
        end
      end

      def validate_owner
        unless(@project.owner?(current_user))
          redirect_to project_path(@project), notice: "Only Project Owner can edit this Project"
        end
      end

  end
end

app/controllers/concerns/projects/setter.rb
module Projects
  module Setter

    private

      def set_project
        unless (@project = Project.find_by_permalink(params[:id]))
          redirect_to root_path, "No Project Found"
        end
      end

      def validate_owner
        unless(@project.owner?(current_user))
          redirect_to project_path(@project), notice: "Only Project Owner can edit this Project"
        end
      end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Projects::Callbacks

  before_action :set_project, only: [:show, :destroy, :backers, :new_message, :edit, :update, :info, :create_info]
  skip_before_action :authorize, only: [:show, :index, :this_week, :category, :location, :backers]
  before_action :validate_owner, only: [:edit, :update, :destroy]
  before_action :check_accessibility, only: [:show]
  before_action :set_location, only: [:create]
  before_action :check_project_state, only: [:edit, :update]

  def this_week
    @projects = Project.includes(:images).live_this_week.page(params[:page]).per_page(PER_PAGE)
    render action: :index
  end

  def index
    @projects = Project.includes(:images).live.order(updated_at: :desc).page(params[:page]).per_page(PER_PAGE)
  end

  def category
    if params[:category].present? && @category = Category.find_by_permalink(params[:category])
      @projects = @category.projects.includes(:images).live.order(updated_at: :desc).page(params[:page]).per_page(PER_PAGE)
    end
    render action: :index
  end

  def location
    if params[:location].present? && @location = Location.find_by_permalink(params[:location])
      @projects = @location.projects.includes(:images).live.order(updated_at: :desc).page(params[:page]).per_page(PER_PAGE)
    end
    render action: :index
  end

  def new
    @project = Project.new
    if @project.images.empty?
      @image = @project.images.build
    else
      @image = @project.images
    end
    if @project.location.nil?
      @location = @project.build_location
    else
      @location = @project.location
    end
  end

  def show
  end

  def user_owned
    @projects = current_user.owned_projects.includes(:images)
  end

  def edit
    if @project.images.empty?
      @image = @project.images.build
    else
      @image = @project.images
    end
    @project.edit! if !@project.draft?
  end

  def new_message
  end

  def info
  end

  def create_info
    if @project.save_info(project_params)
      redirect_to rewards_project_path(@project)
    else
      render action: :info
    end
  end

  def create
    @project = build_project_from_location(@location, project_params)
    if @project.present? && @project.save_primary_details(current_user)
      redirect_to story_project_path(@project)
    else
      @project = Project.new(project_params)
      if @project.invalid?
        render action: :new
      end
    end
  end

  def update
    @project.step = 1
    if @project.update(project_params)
      redirect_to story_project_path(@project)
    else
      render action: :edit
    end
  end

  def destroy
    begin
      @project.destroy
      flash[:notice] = "Project #{@project.title} deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    redirect_to root_path
  end

  def new_reward
  end

  def backers
    respond_to do |format|
      format.json { render json: @project.pledges.to_json(:include => { :user => { :only => :name } }, :only => ["amount", "created_at"]) }
    end
  end

  def new_image
  end

  private

  def check_accessibility
    if current_user_owner_or_admin?
      nil
    elsif !@project.approved?
      redirect_to projects_path, notice: "Access Denied"
    elsif @project.outdated?
      redirect_to projects_path, notice: "Outdated project"
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :image, :category_id, :summary, :video_url, :duration, :deadline, :goal, :published_at, :images_attributes => [:id, :attachment], :location_attributes => [:id, :name])
  end

  def validate_not_owner
    if(@project.owner?(current_user))
      redirect_to project_path(@project), notice: "You cannot pledge for your own project"
    end
  end

  def current_user_owner_or_admin?
    logged_in? && (@project.owner?(current_user) || current_user.admin?)
  end

  def set_location
    if project_params[:location_attributes][:name].present?
      @location = Location.find_or_create_by(name: project_params[:location_attributes][:name])
    end
  end

  def build_project_from_location(location, build_params)
    if location.present? && location.persisted?
      @project = location.projects.build(build_params)
    end
  end

  def check_project_state
    unless @project.draft? || @project.submitted?
      redirect_to project_path(@project), notice: 'Project cannot be edited'
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def raw_sanitized_text(text)
    raw sanitize(text, attributes: %w'style class id')
  end

end

app/views/admin/projects/_details.html.erb
<div id="admin-buttons" class="highlight high300">

  <% if project.approved? %>
    <div id="approve-button" class="text-center">
      Project Approved
    </div>
  <% elsif project.rejected? %>
    <div id="reject-button" class="text-center">
      Project Rejected
    </div>
  <% else %>
    <div id="approve-button" class="large-button text-center">
      <%= link_to "Approve Project", approve_admin_project_path(project), remote: true %>
    </div>
    <div id="reject-button" class="large-button text-center">
      <%= link_to "Reject Project", reject_admin_project_path(project), remote: true %>
    </div>
  <% end %>
</div>

app/views/admin/projects/approve.js.erb
$('#admin-buttons').html("");
$('<div id="approve-button"></div>').appendTo('#admin-buttons').removeClass('large-button').html('Project Approved');

app/views/admin/projects/index.html.erb
<%- @pending_projects = @projects.submitted -%>
<%- @rejected_projects = @projects.rejected -%>
<%- @approved_projects = @projects.approved -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Projects" %></h1>
</div>
<ul class="nav nav-pills tabbable">
  <li class="active"><a href="#pending-projects" data-toggle="tab">Pending Projects</a></li>
  <li><a href="#rejected-projects" data-toggle="tab">Rejected Projects</a></li>
  <li><a href="#approved-projects" data-toggle="tab">Approved Projects</a></li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12 tab-content">
      <div id="pending-projects" class="container-fluid tab-pane active">
        <h3>Projects Pending for Approval</h3>
        <% if @pending_projects.empty? %>
          <p>No Pending Projects here</p>
        <% else %>
          <%= render partial: 'projects/listing', locals: { :projects => @pending_projects } %>
          <%= will_paginate @pending_projects %>
        <% end %>
      </div>
      <div id="rejected-projects" class="container-fluid tab-pane">
        <h3>Rejected Projects</h3>
        <% if @rejected_projects.empty? %>
          <p>No Rejected Projects here</p>
        <% else %>
          <%= render partial: 'projects/listing', locals: { :projects => @rejected_projects } %>
          <%= will_paginate @rejected_projects %>
        <% end %>
      </div>
      <div id="approved-projects" class="container-fluid tab-pane">
        <h3>Approved Projects</h3>
        <% if @approved_projects.empty? %>
          <p>No Approved Projects till now</p>
        <% else %>
          <%= render partial: 'projects/listing', locals: { :projects => @approved_projects } %>
          <%= will_paginate @approved_projects %>
        <% end %>
      </div>
    </div>
    <div class="span3">
    </div>
  </div>
</div>

app/views/admin/projects/pending_for_approval.html.erb
<%- @pending_projects = @projects["submitted"].select { |project| project.deadline > Time.current } -%>
<%- @rejected_projects = @projects["rejected"] -%>
<%- @approved_projects = @projects["approved"] -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Projects" %></h1>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span9">
      <div class="container-fluid">
        <h3>Projects Pending for Approval</h3>
        <% if @pending_projects.empty? %>
          <p>No Pending Projects for Approval</p>
        <% else %>
          <%= render partial: 'projects/listing', locals: { :projects => @pending_projects } %>
        <% end %>
      </div>
      <hr>
      <div class="container-fluid">
        <h3>Rejected Projects</h3>
        <% if @rejected_projects.empty? %>
          <p>No Rejected Projects till now</p>
        <% else %>
          <%= render partial: 'projects/listing', locals: { :projects => @rejected_projects } %>
        <% end %>
      </div>
      <hr>
      <div class="container-fluid">
        <h3>Approved Projects</h3>
        <% if @approved_projects.empty? %>
          <p>No Approved Projects till now</p>
        <% else %>
          <%= render partial: 'projects/listing', locals: { :projects => @approved_projects } %>
        <% end %>
      </div>
    </div>
    <div class="span3">
    </div>
  </div>
</div>

app/views/admin/projects/reject.js.erb
$('#admin-buttons').html("");
$('<div id="reject-button"></div>').appendTo('#admin-buttons').removeClass('large-button').html('Project Rejected');