config/routes.rb
Kickstarter::Application.routes.draw do
  resources :subscriptions, only: [:new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  root :to => 'projects#index'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
  end
  match 'auth/:provider/callback', to: 'sessions#facebook_create', provider: 'facebook', via: [:get, :post], as: :facebook_callback
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  match "/contacts/gmail/get_contacts", controller: "contacts", action: "gmail_callback", via: [:get, :post]
  match "/contacts/failure", controller: "contacts", action: "failure", via: [:get, :post]
  post "send_email", controller: "contacts"
  namespace :payment do
    namespace :stripe do
      get "charges/new_card"
      post "charges", controller: 'charges', action: 'create_card'
    end
    namespace :paypal do
      match "notify", controller: 'notifications', action: 'create', via: [:get, :post]
    end
  end

  match 'search', controller: 'searches', action: 'search', via: :get, as: :search_results

  resources :projects do
    get "/contacts_import_instructions", controller: "contacts", action: "import_instructions", on: :member
    get "/get_gmail_contacts", controller: "contacts", action: "get_gmail_contacts", on: :member
    match 'category/:category', action: 'category', via: [:get, :post], on: :collection
    match 'location/:location', action: 'location', via: [:get, :post], on: :collection
    get 'rewards/choose', on: :member, controller: 'rewards', action: 'choose'
    get 'this_week', on: :collection
    get 'new_message', on: :member, as: :new_message
    get 'back', on: :member
    get 'pledge', controller: 'pledges', action: 'new', on: :member
    post 'create_pledge', controller: 'pledges', action: 'create', on: :member
    get 'new_reward', on: :collection
    get 'new_image', on: :collection
    get 'story', controller: 'stories', action: 'new', on: :member
    get 'info', on: :member
    get 'rewards', controller: 'rewards', action: 'new', on: :member
    patch 'create_story', controller: 'stories', action: 'create', on: :member
    patch 'create_info', on: :member
    patch 'create_rewards', controller: 'rewards', action: 'create', on: :member
    get 'admin_conversation', controller: 'admin/messages', action: 'index', on: :member
    post 'create_admin_conversation', controller: 'admin/messages', action: 'create', on: :member
    get 'description', on: :member
    get 'backers', on: :member
  end
  get "my_projects", to: 'projects#user_owned'

  get '/admin', controller: 'sessions', action: 'new', as: :admin_root
  namespace :admin do
    get "users", action: 'index', controller: :users
    delete "users", action: 'destroy', controller: :users
    post "users/:id/make_admin", action: 'make_admin', controller: :users, as: :make_admin
    resources :projects, only: [:index] do
      get "approve", on: :member
      get "reject", on: :member
    end
  end

  resources :messages, only: [:index, :show] do
    post "create", on: :member, as: :create
  end

  resources :users, only: [:create, :show, :update] do
    get "signup", to: 'users#new', on: :collection
    get "/edit_profile", to: 'users#edit', as: :edit, on: :member
  end

  

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  summary       :string(300)
#  location_name :string(255)
#  duration      :integer
#  deadline      :datetime
#  goal          :integer
#  created_at    :datetime
#  updated_at    :datetime
#  owner_id      :integer
#  category_id   :integer
#  published_at  :datetime
#  video_url     :string(255)
#  project_state :string(255)
#  permalink     :string(255)
#  deleted_at    :time
#  location_id   :integer
#

class Project < ActiveRecord::Base
  include ThinkingSphinx::Scopes
  after_save ThinkingSphinx::RealTime.callback_for(:project)
  after_destroy ThinkingSphinx::RealTime.callback_for(:project)

  with_options if: -> { first_step? || step_not_set? } do |project|
    project.validates :title, uniqueness: { case_sensitive: false }, length: { maximum: 60 }
    project.validates :title, :summary, :location, presence: true
    project.validates :summary, length: { maximum: 300 }
    project.validates_associated :location
  end

  with_options if: -> { third_step? || step_not_set? } do |project|
    project.validates :goal, :duration, :published_at, presence: true
    project.validates :goal, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_blank: true
    project.validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: PAYMENT_HOLDING_PERIOD }, allow_blank: true
    # project.validate :future_publish_date
  end
  
  validates_associated :story, if: -> { second_step? || step_not_set? }
  validates_associated :rewards, if: -> { fourth_step? || step_not_set? }

  has_many :rewards
  has_one :story, validate: false
  belongs_to :owner, foreign_key: "owner_id", class_name: 'User'
  belongs_to :category
  has_many :messages
  belongs_to :location, validate: false
  has_many :images, inverse_of: :project
  has_many :pledges, -> { joins(:transaction) }
  has_many :backers, -> { uniq },through: :pledges, source: :user

  accepts_nested_attributes_for :rewards, update_only: true
  accepts_nested_attributes_for :story, update_only: true
  accepts_nested_attributes_for :location, update_only: true
  accepts_nested_attributes_for :messages
  accepts_nested_attributes_for :images, reject_if: proc { |attributes| attributes[:attachment].blank? }
  accepts_nested_attributes_for :pledges

  scope :published, ->(time) { where(['published_at <= ?', time]) }
  scope :published_between, ->(start_time, end_time) { where(['published_at <= ? OR published_at >= ?', start_time, end_time]) }
  scope :still_active, -> { where(['deadline >= ?', Time.current]) }
  scope :located_in, ->(place) { joins(:location).where(:locations => { name: place}) }
  scope :owned_by, ->(user) { where(owner_id: user.id) }
  scope :live, -> { approved.published(Time.current).still_active }
  scope :live_for_user, ->(user) { live.where(owner_id: user.id) }
  scope :pending_for_approval, -> { submitted.still_active.order('created_at ASC') }
  scope :live_this_week, -> { approved.published_between(Time.current, 1.week.ago).still_active }
  scope :for_page, ->(page_number) { page(page_number).per_page(PER_PAGE) }

  sphinx_scope(:been_approved) { { :conditions => { :project_state => 'approved' } } }
  sphinx_scope(:active) { { :with => { :deadline => Time.current..1.month.from_now, :published_at => 1.month.ago..Time.current } } }

  before_save :set_deadline
  before_save :convert_to_youtube_embed_link

  acts_as_paranoid

  has_permalink :title, true

  include AASM

  aasm column: 'project_state' do
    state :draft, initial: true
    state :submitted
    state :approved
    state :rejected
    state :funding_successful
    state :funding_unsuccessful

    event :submit do
      transitions :from => :draft, :to => :submitted
    end

    event :approve do
      before do
        self.published_at = Time.current if published_at.nil? || published_at < Time.current
        self.deadline = published_at + duration.days
      end
      transitions :from => :submitted, :to => :approved
      after do
        set_publishing_delayed_job
        set_funding_delayed_job
      end
    end

    event :edit do
      transitions :from => :submitted, :to => :draft
    end

    event :reject do
      transitions :from => :submitted, :to => :rejected
    end

    event :completely_funded do
      transitions :from => :approved, :to => :funding_successful
      after do
        ProjectStatusNotifier.funded(self).deliver
      end
    end

    event :failed_funding_goal do
      transitions :from => :approved, :to => :funding_unsuccessful
      after do
        ProjectStatusNotifier.failed(self).deliver
      end
    end

  end

  # Converts any standard youtube link to equivalent embed link
  # eg. Youtube Link: http://www.youtube.com/watch?v=8SbUC-UaAxE&list=TLzRodY7MxKM0Hs7zgM0ueePM1_MzGI3h5
  # Embed Link: http://www.youtube.com/embed/8SbUC-UaAxE
  def convert_to_youtube_embed_link
    self.video_url.gsub!(/(youtube.com\/)(.)*v=([\w\-_]+)(.)*$/, '\1embed/\3')
  end

  def set_deadline
    if fourth_step?
      self.deadline = Time.current + duration.to_i.days
    end
  end

  def future_publish_date
    if published_at.nil? || published_at < Time.current
      errors.add :published_at, 'has to be after today'
    end
  end

  def step?(number)
    step == number
  end

  def step_not_set?
    step.nil?
  end

  def first_step?
    step?(1)
  end

  def second_step?
    step?(2)
  end

  def third_step?
    step?(3)
  end

  def fourth_step?
    step?(4)
  end

  def set_publishing_delayed_job
    Delayed::Job.enqueue(PublishProjectJob.new(self), run_at: published_at)
  end

  def set_funding_delayed_job
    Delayed::Job.enqueue(ProjectFundingJob.new(self), run_at: deadline)
  end

  def owner?(user)
    owner_id == user.id
  end

  def save_primary_details(project_creator)
    generate_permalink!
    self.owner = project_creator
    self.step = 1
    save
  end

  def save_story(params)
    self.step = 2
    update(params)
  end

  def save_info(params)
    self.step = 3
    update(params)
  end

  def save_rewards(params)
    self.step = 4
    update(params)
    submit!
  end

  def outdated?
    deadline <= Time.current
  end

  def thumbnail
    if images.present?
      images[0].attachment.url(:thumb)
    else
      '/images/thumb/missing.png'
    end
  end

  def youtube_video?
    video_url.present? && video_url.match(/youtube\.com/)
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  include Projects::Callbacks

  before_action :set_project, only: [:approve, :reject]

  def index
    @projects = Project.includes(:images).order('updated_at DESC').page(params[:page]).per_page(PER_PAGE)
  end

  def approve
    unless @project.approve!
      flash[:alert] = 'The project could not be approved'
      #FIXME_AB: Why do we need render js in these two actions, we have the erb.js files for these actions
      #FIXED: In case project fails to be accepted or rejected, it should display error message and not js.erb file
      render js: %(window.location.href = '#{ project_path(@project) }')
    end
  end

  def reject
    unless @project.reject!
      flash[:alert] = 'The project failed to be rejected'
      render js: %(window.location.href = '#{ project_path(@project) }')
    end
  end

end

app/controllers/concerns/projects/callbacks.rb
module Projects
  module Callbacks

    private

      def set_project
        unless (@project = Project.find_by_permalink(params[:id]))
          redirect_to root_path, alert: "No Project Found"
        end
      end

      def validate_owner
        unless(@project.owner?(current_user))
          redirect_to project_path(@project), notice: "Only Project Owner can edit this Project"
        end
      end

  end
end

app/controllers/concerns/projects/setter.rb
module Projects
  module Setter

    private

      def set_project
        unless (@project = Project.find_by_permalink(params[:id]))
          redirect_to root_path, "No Project Found"
        end
      end

      def validate_owner
        unless(@project.owner?(current_user))
          redirect_to project_path(@project), notice: "Only Project Owner can edit this Project"
        end
      end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Projects::Callbacks

  before_action :set_project, only: [:show, :destroy, :backers, :new_message, :edit, :update, :info, :create_info]
  skip_before_action :authorize, only: [:show, :index, :this_week, :category, :location, :backers]
  before_action :validate_owner, only: [:edit, :update, :destroy]
  before_action :check_accessibility, only: [:show]
  before_action :set_location, only: [:create]
  before_action :check_project_state, only: [:edit, :update]

  def this_week
    @projects = Project.includes(:images).live_this_week.page(params[:page]).per_page(PER_PAGE)
    render action: :index
  end

  def index
    @projects = Project.includes(:images).live.order(updated_at: :desc).page(params[:page]).per_page(PER_PAGE)
  end

  def category
    if params[:category].present? && @category = Category.find_by_permalink(params[:category])
      @projects = @category.projects.includes(:images).live.order(updated_at: :desc).page(params[:page]).per_page(PER_PAGE)
    end
    render action: :index
  end

  def location
    if params[:location].present? && @location = Location.find_by_permalink(params[:location])
      @projects = @location.projects.includes(:images).live.order(updated_at: :desc).page(params[:page]).per_page(PER_PAGE)
    end
    render action: :index
  end

  def new
    @project = Project.new
    if @project.images.empty?
      @image = @project.images.build
    else
      @image = @project.images
    end
    if @project.location.nil?
      @location = @project.build_location
    else
      @location = @project.location
    end
  end

  def show
  end

  def user_owned
    @projects = current_user.owned_projects.includes(:images)
  end

  def edit
    if @project.images.empty?
      @image = @project.images.build
    else
      @image = @project.images
    end
    @project.edit! if !@project.draft?
  end

  def new_message
  end

  def info
  end

  def create_info
    if @project.save_info(project_params)
      redirect_to rewards_project_path(@project)
    else
      render action: :info
    end
  end

  def create
    @project = build_project_from_location(@location, project_params)
    if @project.present? && @project.save_primary_details(current_user)
      redirect_to story_project_path(@project)
    else
      @project = Project.new(project_params)
      if @project.invalid?
        render action: :new
      end
    end
  end

  def update
    @project.step = 1
    if @project.update(project_params)
      redirect_to story_project_path(@project)
    else
      render action: :edit
    end
  end

  def destroy
    begin
      @project.destroy
      flash[:notice] = "Project #{@project.title} deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    redirect_to root_path
  end

  def new_reward
  end

  def backers
    respond_to do |format|
      format.json { render json: @project.pledges.to_json(:include => { :user => { :only => :name } }, :only => ["amount", "created_at"]) }
    end
  end

  def new_image
  end

  private

  def check_accessibility
    if current_user_owner_or_admin?
      nil
    elsif !@project.approved?
      redirect_to projects_path, notice: "Access Denied"
    elsif @project.outdated?
      redirect_to projects_path, notice: "Outdated project"
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :image, :category_id, :summary, :video_url, :duration, :deadline, :goal, :published_at, :images_attributes => [:id, :attachment], :location_attributes => [:id, :name])
  end

  def validate_not_owner
    if(@project.owner?(current_user))
      redirect_to project_path(@project), notice: "You cannot pledge for your own project"
    end
  end

  def current_user_owner_or_admin?
    logged_in? && (@project.owner?(current_user) || current_user.admin?)
  end

  def set_location
    if project_params[:location_attributes][:name].present?
      @location = Location.find_or_create_by(name: project_params[:location_attributes][:name])
    end
  end

  def build_project_from_location(location, build_params)
    if location.present? && location.persisted?
      @project = location.projects.build(build_params)
    end
  end

  def check_project_state
    unless @project.draft? || @project.submitted?
      redirect_to project_path(@project), notice: 'Project cannot be edited'
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def raw_sanitized_text(text)
    raw sanitize(text, attributes: %w'style class id')
  end

end

app/views/projects/_backers.html.erb
<div id="pledges" class="container-fluid">
  <h3>Pledges</h3>
  <div id="backers">
    <% if @pledges.present? %>
      <% @pledges.each do |pledge| %>
        <div class="row">
          <div class="span8 highlight">
            <p><%= link_to pledge.user.name, user_path(pledge.user.id) %> pledged <%= number_to_currency(pledge.amount) %> for the project <%= pledge.project.title %> on <%= pledge.created_at.strftime('%v') %>(<%= pledge.created_at.strftime('%I:%M %p') %>)</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/_details.html.erb
<div class="highlight high470">
  <%- backers_count = project.backers.count -%>
  <h2 id="backer-count"><%= backers_count %></h2>
  <p><%= "backer".pluralize(backers_count) %></p>
  <h2 id="goal-required"><%= number_to_currency(project.goal) %></h2>
  <p>funding required</p>
  <h2 id="goal-achieved"><%= number_to_currency(project.pledges.sum(:amount)) %></h2>
  <p>amount funded</p>
  <div class="text-center">
    <% if logged_in? && !project.owner?(current_user) %>
      <% total_pledged_amount = current_user.pledge_amount_for_project(project) %>
      <% if total_pledged_amount != 0 %>
        <div id="pledge-info" class="text-center">
          <%= "You have pledged #{number_to_currency(total_pledged_amount)} for this project." %>
        </div>
      <% end %>
        <div id="pledge-button" class="large-button text-center">
          <%= link_to "Pledge for this project", pledge_project_path(project) %>
        </div>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<% @project.errors.delete(:"images.attachment") if @project.errors.present? %>
<%= get_errors(@project) %>
<%= form_for @project, :url => form_path, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field', :required => true %>
      <p class="help-block">Enter the title of your project</p>
    </div>
  </div>
  <%= f.fields_for :images, @image do |image| %>
    <div class="control-group">
      <%= image.label :attachment, :Image, :class => 'control-label' %>
      <div class="project-image">
        <div class="controls">
          <%= image.file_field :attachment, :class => 'text_field' %>
          <p class="help-block">Formats: JPG, GIF, PNG ; Size: upto 200 kB</p>
        </div>
      </div>
      <div class="controls">
        <div class="add-link">
          <%= link_to "Add Image", new_image_projects_path, remote: true %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :category_id, Category.all, :id, :name %>
      <p class="help-block">Select category for your project</p>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :summary, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.text_area :summary, :class => 'text_field', :maxlength => '300', :required => true %>
      <p class="help-block">Enter a short description in about 300 characters about your project</p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :video_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.url_field :video_url, :class => 'url_field' %>
      <p class="help-block">Enter a youtube video link about your project</p>
    </div>
  </div>

  <%= f.fields_for :location, @location do |location| %>
    <div class="control-group">
      <%= location.label :name, :City, :class => 'control-label' %>
      <span class='required'>*</span>
      <div class="controls">
        <%= location.text_field :name, :class => 'text_field', :required => true %>
          <p class="help-block">Enter the location of your project</p>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <span class='required'>*</span><span> marks required fields</span>
    </div>
  </div>

  <%= render partial: 'projects/steps_covered' %>

  <div class="form-actions">
    <%= link_to 'Cancel', projects_path, :class => 'btn' %>
    <%= f.submit "Next >", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/_image_field.html.erb
<%- @time = Time.current.to_i -%>
<div class="project-images">
  <div class="controls">
    <input type="file" name="project[images_attributes][<%= @time %>][attachment]" id="project_images_attributes_<%= @time %>_attachment" class="text_field">
  </div>
</div>

app/views/projects/_listing.html.erb
<% if projects.present? %>
  <% cache projects do %>
    <div class="row-fluid">
    <% projects.each do |project| %>
      <div class="small-box">
        <% cache project do %>
          <%= render partial: 'projects/short_description', locals: { :project => project } %>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
<% else %>
  <p>No projects here.</p>
<% end %>

app/views/projects/_short_description.html.erb
<div class="highlight high300">
  <div class="highlight-inner">
    <%= image_tag project.thumbnail, class: 'project-thumbnail' %>
    <h5 class='text-center'><%= link_to project.title, project_path(project) %></h5>
    <p><%= truncate(project.summary, length: 125) %></p>
  </div>
</div>

app/views/projects/_steps_covered.html.erb
  <div class="control-group">
    <div class="controls">
      <%if @project.persisted? %>
        Go to:
        <%if @project.step >= 1 %>
          <%= link_to 'Step 1', edit_project_path(@project) %>
        <% end %>
        <%if @project.step >= 2 %>
          <%= link_to 'Step 2', story_project_path(@project) %>
        <% end %>
        <%if @project.step >= 3 %>
          <%= link_to 'Step 3', info_project_path(@project) %>
        <% end %>
        <%if @project.step == 4 %>
          <%= link_to 'Step 4', rewards_project_path(@project) %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/projects/edit.html.erb
<%- @location = @project.location -%>
<div class="page-header">
  <h1><%=t '.title', :default => 'Edit Project' %></h1>
</div>
<%= render :partial => 'form', locals: { :form_path => project_path } %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Discover <%=t '.title', :default => "Projects" %></h1>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span9">
      <% #FIXME_AB: Should you form_for helper. You said it adds some more params to url, what are those? -%>
      <form action="<%= search_results_path %>" method="get">
        <%= text_field_tag :q, params[:q], placeholder: 'Search projects...', style: 'margin-bottom:0px;' %>
        <%= submit_tag "Search", name: nil, class: 'btn btn-primary' %>
      </form>
    </div>
  </div>
</div>
<% if @projects.present? %>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <%= render partial: 'projects/listing', locals: { :projects => @projects } %>
        <%= will_paginate @projects %>
      </div>
    </div>
  </div>
<% elsif params[:q].present? %>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <h4><%= "No Projects found containing the search term '#{ params[:q] }'" %></h4>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <h4><%= "No Projects to display" %></h4>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => 'New Project' %></h1>
</div>
<%= render :partial => 'form', locals: { :form_path => projects_path } %>

app/views/projects/new_image.js.erb
var $projectImages = $('.project-image');
$('<div class="project-image"></div>').insertAfter($projectImages.last()).html("<%= escape_javascript(render partial: 'projects/image_field') %>");

app/views/projects/new_reward.js.erb
var $projectRewards = $('.project-reward');
$('<div class="project-reward"></div>').insertAfter($projectRewards.last()).html("<h5>Reward #" + ($projectRewards.length + 1) + "</h5><%= escape_javascript(render partial: 'rewards/project_fields') %>");

app/views/projects/show.html.erb
<%-  @story = @project.story -%>
<%- @rewards = @project.rewards -%>
<%- @owner = @project.owner -%>
  <div class="page-header center">
    <h2 class="text-center"><%= @project.title %></h2>
    <h5 class="text-center">By <%= @project.owner.name %></h5>
    <div class="container-fluid navbar">
      <ul class="nav pull-left">
        <li id="description-button"><a class="linkable">Description</a></li>
        <% if logged_in? && (current_user.admin? || (@project.owner?(current_user)) ) %>
          <%= menu_divider %>
          <li id="messages-button" data-new-message-link="<%= new_message_project_url(@project) %>" data-new-message-link-show="<%= current_user.admin? ? "1" : "0" %>"><a class="linkable">Messages</a></li>
        <% end %>
        <%= menu_divider %>
        <li id="pledges-button"><a class="linkable">Pledges</a></li>
      </ul>
      <ul class="nav pull-right">
        <li class="no-link"><%= @project.location_name %></li>
        <% if logged_in? && (@project.owner?(current_user)) %>
          <% if @project.draft? || @project.submitted? %>
            <%= menu_divider %>
            <li><%= link_to "Edit Project", edit_project_path(@project)  %></li>
          <% elsif @project.approved? %>
            <%= menu_divider %>
            <li><%= link_to "Promote Project", contacts_import_instructions_project_path(@project) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>


<div class="span8" id="project-main">
  <div id="description">
    <%= cache @project do %>
      <%= render partial: 'description' %>
    <% end %>
  </div>
</div>
<div class="span3">
  <% if logged_in? && current_user.admin? %>
    <%= render partial: 'admin/projects/details', locals: { :project => @project } %>
  <% else %>
    <%= render partial: 'details', locals: { :project => @project } %>
    <%= render partial: 'users/fields', locals: { :user => @owner } %>
  <% end %>
</div>

app/views/projects/user_owned.html.erb
<%- @pending_projects = @projects.submitted -%>
<%- @approved_projects = @projects.approved -%>
<%- @draft_projects = @projects.draft -%>
<%- @rejected_projects = @projects.rejected -%>
<div class="page-header">
  <h1>My <%=t '.title', :default => "Projects" %></h1>
</div>
<ul class="nav nav-pills tabbable">
  <li class="active"><a href="#draft-projects" data-toggle="tab">Draft Projects</a></li>
  <li><a href="#pending-projects" data-toggle="tab">Pending Projects</a></li>
  <li><a href="#rejected-projects" data-toggle="tab">Rejected Projects</a></li>
  <li><a href="#approved-projects" data-toggle="tab">Approved Projects</a></li>
</ul>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12 tab-content">
      <div id="draft-projects" class="container-fluid tab-pane active">
        <h3>Draft Projects</h3>
        <%= render partial: 'projects/listing', locals: { :projects => @draft_projects } %>
      </div>
      <div id="rejected-projects" class="container-fluid tab-pane">
        <h3>Rejected Projects</h3>
        <%= render partial: 'projects/listing', locals: { :projects => @rejected_projects } %>
      </div>
      <div id="pending-projects" class="container-fluid tab-pane">
        <h3>Projects Pending for Approval</h3>
        <%= render partial: 'projects/listing', locals: { :projects => @pending_projects } %>
      </div>
      <div id="approved-projects" class="container-fluid tab-pane">
        <h3>Approved Projects</h3>
        <%= render partial: 'projects/listing', locals: { :projects => @approved_projects } %>
      </div>
    </div>
  </div>
</div>