config/routes.rb
Kickstarter::Application.routes.draw do
  resources :subscriptions, only: [:new, :create]
  mount Ckeditor::Engine => '/ckeditor'
  root :to => 'projects#index'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
  end
  match 'auth/:provider/callback', to: 'sessions#facebook_create', provider: 'facebook', via: [:get, :post], as: :facebook_callback
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  match "/contacts/gmail/get_contacts", controller: "contacts", action: "gmail_callback", via: [:get, :post]
  match "/contacts/failure", controller: "contacts", action: "failure", via: [:get, :post]
  post "send_email", controller: "contacts"
  namespace :payment do
    namespace :stripe do
      get "charges/new_card"
      post "charges", controller: 'charges', action: 'create_card'
    end
    namespace :paypal do
      match "notify", controller: 'notifications', action: 'create', via: [:get, :post]
    end
  end

  match 'search', controller: 'searches', action: 'search', via: :get, as: :search_results

  resources :projects do
    get "/contacts_import_instructions", controller: "contacts", action: "import_instructions", on: :member
    get "/get_gmail_contacts", controller: "contacts", action: "get_gmail_contacts", on: :member
    match 'category/:category', action: 'category', via: [:get, :post], on: :collection
    match 'location/:location', action: 'location', via: [:get, :post], on: :collection
    get 'rewards/choose', on: :member, controller: 'rewards', action: 'choose'
    get 'this_week', on: :collection
    get 'new_message', on: :member, as: :new_message
    get 'back', on: :member
    get 'pledge', controller: 'pledges', action: 'new', on: :member
    post 'create_pledge', controller: 'pledges', action: 'create', on: :member
    get 'new_reward', on: :collection
    get 'new_image', on: :collection
    get 'story', controller: 'stories', action: 'new', on: :member
    get 'info', on: :member
    get 'rewards', controller: 'rewards', action: 'new', on: :member
    patch 'create_story', controller: 'stories', action: 'create', on: :member
    patch 'create_info', on: :member
    patch 'create_rewards', controller: 'rewards', action: 'create', on: :member
    get 'admin_conversation', controller: 'admin/messages', action: 'index', on: :member
    post 'create_admin_conversation', controller: 'admin/messages', action: 'create', on: :member
    get 'description', on: :member
    get 'backers', on: :member
  end
  get "my_projects", to: 'projects#user_owned'

  get '/admin', controller: 'sessions', action: 'new', as: :admin_root
  namespace :admin do
    get "users", action: 'index', controller: :users
    delete "users", action: 'destroy', controller: :users
    post "users/:id/make_admin", action: 'make_admin', controller: :users, as: :make_admin
    resources :projects, only: [:index] do
      get "approve", on: :member
      get "reject", on: :member
    end
  end

  resources :messages, only: [:index, :show] do
    post "create", on: :member, as: :create
  end

  resources :users, only: [:create, :show, :update] do
    get "signup", to: 'users#new', on: :collection
    get "/edit_profile", to: 'users#edit', as: :edit, on: :member
  end

  

end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id               :integer          not null, primary key
#  description      :text
#  risks            :text
#  created_at       :datetime
#  updated_at       :datetime
#  project_id       :integer
#  why_we_need_help :text
#  faq              :text
#  about_the_team   :text
#

class Story < ActiveRecord::Base
  after_save ThinkingSphinx::RealTime.callback_for(:project, [:project])
  after_destroy ThinkingSphinx::RealTime.callback_for(:project, [:project])

  validates :description, :risks, :why_we_need_help, :faq, :about_the_team, presence: true

  belongs_to :project

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  include Projects::Callbacks

  before_action :set_project, only: [:new, :create]
  before_action :validate_owner, only: [:new, :create]

  def new
    if @project.story.nil?
      @story = @project.build_story
    else
      @story = @project.story
    end
  end

  def create
    if @project.save_story(project_params)
      redirect_to info_project_path(@project)
    else
      @story = @project.story
      render action: :new
    end
  end

  private

    def project_params
      params.require(:project).permit(:story_attributes => [:id, :description, :risks, :why_we_need_help, :about_the_team, :faq])
    end

end

app/views/stories/_fields.html.erb
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.cktext_area :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :why_we_need_help, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.cktext_area :why_we_need_help, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :risks, 'Risks and Challenges', :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.cktext_area :risks, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :about_the_team, :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.cktext_area :about_the_team, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :faq, 'FAQs', :class => 'control-label' %>
    <span class='required'>*</span>
    <div class="controls">
      <%= f.cktext_area :faq, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <span class='required'>*</span><span> marks required fields</span>
    </div>
  </div>

app/views/stories/new.html.erb
<%= get_errors(@story) %>
<%= form_for @project, :url => create_story_project_path, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="highlight">
    <h4>Story</h4>
    <%= f.fields_for :story, @story do |builder| %>
      <%= render partial: 'stories/fields', :locals => { :f => builder } %>
    <% end %>
  </div>

  <%= render partial: 'projects/steps_covered' %>

  <div class="form-actions">
    <%= link_to "< Prev", edit_project_path(@project), :class => 'btn' %>
    <%= f.submit "Next >", :class => 'btn btn-primary' %>
  </div>
<% end %>